//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stepTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tested
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string remarks { get; set; }
        public string hearthRate { get; set; }
        public bool readynessToEx { get; set; }
        public bool contraIndication { get; set; }
        public bool lifestyleActlvl { get; set; }
        public int SessionId { get; set; }
        public bool sex { get; set; }
    
        public virtual Session SessionSet { get; set; }
    }
}
